config/routes.rb
Rails.application.routes.draw do
  resources :services

  resources :encounters

  resources :bills do
    collection { post :import }
  end

  root 'bills#index'

end

app/models/bill.rb
class Bill < ActiveRecord::Base
  has_many :encounters
end

app/models/encounter.rb
class Encounter < ActiveRecord::Base
    has_many :services
    belongs_to :bill
end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :encounter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  # GET /bills
  # GET /bills.json
  def index
   @bills = Bill.all
   @billsmorethanone = Bill.joins(:encounters).group('bills.id').having("COUNT(encounters.bill_id) >= ?", 2).count
   @avgs = Bill.joins(encounters: :services).average(:cost)
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def import
     uploaded_file = params[:file]
     file_content = uploaded_file.read
     file_content.each_line do |l|
      if l =~ /START OF BILL \d/
        @bill = Bill.create
      else
        if l=~ /Patient\s+(.+)\s+encounter+\swith\s+(.+)/
          regex = /Patient\s+(.+)\s+encounter+\swith\s+(.+)/
          content = l.scan(regex)
          Encounter.create(patient_name: content[0][0], doctor_name: content[0][1], bill_id: Bill.last.id)
        else
          if l=~ /Service\s+(.+)\s+-+\scost\s\$+(.+)/
            regex = /Service\s+(.+)\s+-+\scost\s\$+(.+)/
            content = l.scan(regex)
            @service = Service.create(name: content[0][0], cost: content[0][1], encounter_id: Encounter.last.id)
          end
        end
      end
     end
   #Bill.import(params[:file]).read
    redirect_to bills_path, notice: "success!"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:avg_cost)
    end
end

app/controllers/encounters_controller.rb
class EncountersController < ApplicationController
  before_action :set_encounter, only: [:show, :edit, :update, :destroy]

  # GET /encounters
  # GET /encounters.json
  def index
    @encounters = Encounter.all
  end

  # GET /encounters/1
  # GET /encounters/1.json
  def show
  end

  # GET /encounters/new
  def new
    @encounter = Encounter.new
  end

  # GET /encounters/1/edit
  def edit
  end

  # POST /encounters
  # POST /encounters.json
  def create
    @encounter = Encounter.new(encounter_params)

    respond_to do |format|
      if @encounter.save
        format.html { redirect_to @encounter, notice: 'Encounter was successfully created.' }
        format.json { render :show, status: :created, location: @encounter }
      else
        format.html { render :new }
        format.json { render json: @encounter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /encounters/1
  # PATCH/PUT /encounters/1.json
  def update
    respond_to do |format|
      if @encounter.update(encounter_params)
        format.html { redirect_to @encounter, notice: 'Encounter was successfully updated.' }
        format.json { render :show, status: :ok, location: @encounter }
      else
        format.html { render :edit }
        format.json { render json: @encounter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /encounters/1
  # DELETE /encounters/1.json
  def destroy
    @encounter.destroy
    respond_to do |format|
      format.html { redirect_to encounters_url, notice: 'Encounter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_encounter
      @encounter = Encounter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def encounter_params
      params.require(:encounter).permit(:patient_name, :doctor_name, :bill_id)
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :cost, :encounter_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/encounters_helper.rb
module EncountersHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/bills/_form.html.erb
<%= form_for(@bill) do |f| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :avg_cost %><br>
    <%= f.number_field :avg_cost %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bills/edit.html.erb
<h1>Editing Bill</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<p id="notice"><%= notice %></p>



<br>

Number of Bills with more than one encounter: <%= @billsmorethanone.count %><br>
Average of costs:  <%= @avgs %>

<h3>Import Bills</h3>
<%= form_tag import_bills_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Upload file" %>
<% end %>

<%= link_to 'New Bill', new_bill_path %>

app/views/bills/new.html.erb
<h1>New Bill</h1>

<%= render 'form' %>

<%= link_to 'Back', bills_path %>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Avg cost:</strong>
  <%= @bill.avg_cost %>
</p>

<%= link_to 'Edit', edit_bill_path(@bill) %> |
<%= link_to 'Back', bills_path %>

app/views/encounters/_form.html.erb
<%= form_for(@encounter) do |f| %>
  <% if @encounter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@encounter.errors.count, "error") %> prohibited this encounter from being saved:</h2>

      <ul>
      <% @encounter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :patient_name %><br>
    <%= f.text_field :patient_name %>
  </div>
  <div class="field">
    <%= f.label :doctor_name %><br>
    <%= f.text_field :doctor_name %>
  </div>
  <div class="field">
    <%= f.label :bill_id %><br>
    <%= f.number_field :bill_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/encounters/edit.html.erb
<h1>Editing Encounter</h1>

<%= render 'form' %>

<%= link_to 'Show', @encounter %> |
<%= link_to 'Back', encounters_path %>

app/views/encounters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Encounters</h1>

<table>
  <thead>
    <tr>
      <th>Patient name</th>
      <th>Doctor name</th>
      <th>Bill</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @encounters.each do |encounter| %>
      <tr>
        <td><%= encounter.patient_name %></td>
        <td><%= encounter.doctor_name %></td>
        <td><%= encounter.bill_id %></td>
        <td><%= link_to 'Show', encounter %></td>
        <td><%= link_to 'Edit', edit_encounter_path(encounter) %></td>
        <td><%= link_to 'Destroy', encounter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Encounter', new_encounter_path %>

app/views/encounters/new.html.erb
<h1>New Encounter</h1>

<%= render 'form' %>

<%= link_to 'Back', encounters_path %>

app/views/encounters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Patient name:</strong>
  <%= @encounter.patient_name %>
</p>

<p>
  <strong>Doctor name:</strong>
  <%= @encounter.doctor_name %>
</p>

<p>
  <strong>Bill:</strong>
  <%= @encounter.bill_id %>
</p>

<%= link_to 'Edit', edit_encounter_path(@encounter) %> |
<%= link_to 'Back', encounters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ex</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.number_field :cost %>
  </div>
  <div class="field">
    <%= f.label :encounter_id %><br>
    <%= f.number_field :encounter_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Services</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cost</th>
      <th>Encounter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.name %></td>
        <td><%= service.cost %></td>
        <td><%= service.encounter_id %></td>
        <td><%= link_to 'Show', service %></td>
        <td><%= link_to 'Edit', edit_service_path(service) %></td>
        <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_service_path %>

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form' %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @service.cost %>
</p>

<p>
  <strong>Encounter:</strong>
  <%= @service.encounter_id %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>